django_food_toolbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
url(r'^food_toolbox/', include('food_toolbox.urls')),
    url(r'^admin/', admin.site.urls)
]

food_toolbox/urls.py
from django.conf.urls import url

from . import views

app_name = 'food_toolbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^featured/(?P<recipe_id>[0-9]+)/$', views.featured, name='featured'),
    url(r'^create/$', views.create_recipe, name='create'),
    url(r'^create/(?P<error_message>.+)/$', views.create_recipe, name='create'),
    url(r'^add_recipe/$', views.add_recipe, name='add_recipe'),
    url(r'^add_ingredient/$', views.add_ingredient, name='add_ingredient'),
    url(r'^search/$', views.search, name='search'),
]

food_toolbox/models.py
import datetime

from django.db import models
from django.forms import ModelForm
from django.utils import timezone


class Recipe(models.Model):
    title_text = models.CharField(max_length=200)
    last_modified_date = models.DateField('last modified')
    process_description = models.TextField()
    cooking_temperature_celsius = models.IntegerField(blank=True, null = True)
    preparation_time_minutes = models.IntegerField(blank=True, null = True)
    presentation_image_link = models.URLField(blank=True, null=True)
    def __str__(self):
        return self.title_text

class Ingredients_List(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name

class Recipe_Ingredient(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	ingredient_name = models.ForeignKey(Ingredients_List, on_delete=models.CASCADE)
	ingredient_quantity = models.CharField(max_length=100, blank=True, null=True)
    # def __str__(self):              # __unicode__ on Python 2
    #     return "%s (%s)" % (
    #         self.name,
    #         ", ".join(topping.name for topping in self.toppings.all()),
    #     )

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title_text', 'process_description', 'cooking_temperature_celsius', 'preparation_time_minutes', 'presentation_image_link']
        # labels = {
        #     'name': _('Writer'),
        # }
        # help_texts = {
        #     'name': _('Some useful help text.'),
        # }
        # error_messages = {
        #     'name': {
        #         'max_length': _("This writer's name is too long."),
        #     },
        # }

food_toolbox/views.py
from django.db import IntegrityError
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Recipe, Ingredients_List, RecipeForm, Recipe_Ingredient

def index(request):
	latest_recipe = Recipe.objects.order_by('-last_modified_date')[:1]

	if latest_recipe:
		return redirect('food_toolbox:featured', recipe_id=(latest_recipe[0].id))
	else:
		return redirect('food_toolbox:create')

def featured(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	context = {
			'ingredients_list' : Ingredients_List.objects.order_by('name'),
			'featured_recipe' : recipe,
			'featured_recipe_ingredients' : Recipe_Ingredient.objects.filter(recipe_id=recipe_id)
	}
	return render(request, 'food_toolbox/index.html', context)

def create_recipe(request, error_message=None):
	context = {
			'ingredients_list' : Ingredients_List.objects.order_by('name'),
			'recipe_form' : RecipeForm
	}
	if error_message:
		context['error_message'] = error_message

	return render(request, 'food_toolbox/create.html', context)

def add_recipe(request):
	new_recipe_id = None
	try:
		new_recipe = Recipe(
			title_text = request.POST['title_text'],
			last_modified_date = timezone.now(),
			process_description = request.POST['process_description'])

		if (request.POST['cooking_temperature_celsius']):
			new_recipe.cooking_temperature_celsius = request.POST['cooking_temperature_celsius']
		if (request.POST['preparation_time_minutes']):
			new_recipe.preparation_time_minutes = request.POST['preparation_time_minutes']
		new_recipe.presentation_image_link = request.POST['presentation_image_link']

		new_recipe.save()
		new_recipe_id = new_recipe.id

		for key in request.POST.keys():
			if key.startswith('ingredient'):
				recipe_ingredient = Recipe_Ingredient()
				recipe_ingredient.recipe = new_recipe
				recipe_ingredient.ingredient_name = Ingredients_List(pk=request.POST[key])
				recipe_ingredient.ingredient_quantity = request.POST[request.POST[key]]

				recipe_ingredient.save()

	except IntegrityError as e:
		# TODO Improve error message
		return redirect('food_toolbox:create', error_message="Something went wrong, please try again.")
	else:
		return redirect('food_toolbox:featured', recipe_id=(new_recipe_id))

def add_ingredient(request):
	new_ingredient = Ingredients_List()
	new_ingredient.name = request.POST['ingredient']
	try:
		new_ingredient.save()
	except(IntegrityError):
		return redirect('food_toolbox:create', error_message="Ingredient already exists.")
	else:
		return redirect('food_toolbox:create')

def search(request):
	recipe_relevance_counter = dict()

	for key in request.GET:
		if key.startswith('ingredient'):
			#search by ingredient
			recipe_ingredients_list = Recipe_Ingredient.objects.filter(ingredient_name = request.GET[key])
			for recipe_ingredient in recipe_ingredients_list:
				if recipe_ingredient.recipe.id in recipe_relevance_counter:
					recipe_relevance_counter[recipe_ingredient.recipe.id] += 1
				else:
					recipe_relevance_counter[recipe_ingredient.recipe.id] = 1
		else:
			#search by title/description
			if (request.GET['word_search']):
				recipe_list = Recipe.objects.filter(
					Q(title_text__icontains = request.GET['word_search']) | 
					Q(process_description__icontains = request.GET['word_search']))
				for recipe in recipe_list:
					if recipe.id in recipe_relevance_counter:
						recipe_relevance_counter[recipe.id] += 1
					else:
						recipe_relevance_counter[recipe.id] = 1
	
	if (recipe_relevance_counter):			
		# get last or most relevant
		relevance_values = list(recipe_relevance_counter.values())
		relevance_keys = list(recipe_relevance_counter.keys())
		featured_recipe = relevance_keys[relevance_values.index(max(relevance_values))]

		return redirect('food_toolbox:featured', recipe_id=(featured_recipe))
	else:
		return redirect('food_toolbox:index')

food_toolbox/templates/food_toolbox/create.html
<h1>Insert new recipe</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'food_toolbox:add_recipe'%}" method="post">
	{% csrf_token %}
	{% if ingredients_list %}
		{% for ingredient in ingredients_list %}	
		<input type="checkbox" name="ingredient{{ ingredient.id }}" id="{{ ingredient.id }}" value="{{ ingredient.id}}"/>
		<label for="{{ ingredient.id }}"> {{ ingredient.name }} </label>
		<input type="text" name="{{ ingredient.id}}" id="quantity{{ ingredient.id }}"/>
		<br/>
		{% endfor %}
	{% endif %}
	{{ recipe_form.as_p }}
	<input type="submit" value="Save" />
</form>
<form action="{% url 'food_toolbox:add_ingredient'%}" method="post">
	{% csrf_token %}
	<p>Add new ingredient:</p>
	<input type="text" name="ingredient" required/>
	<input type="submit" value="Add" />
</form>
<a href="{% url 'food_toolbox:index'%}">Cancel</a>

food_toolbox/templates/food_toolbox/index.html
<div id="navigation">
	<a href="{% url 'food_toolbox:create'%}">Add a new recipe</a>
</div>
<div id="search">
	<form method="get" action="{% url 'food_toolbox:search'%}">
		<label for="title_search">Search by title:</label>
        <input type="text" id="word_search" name="word_search"/>  
        <input type="submit" value="Show me some recipes!"/>
        <br/>
        {% if ingredients_list %}
		    {% for ingredient in ingredients_list %}
	        	<input type="checkbox" name="ingredient_{{ ingredient.id }}" id="{{ ingredient.id }}" value="{{ ingredient.id}}"/>
				<label for="{{ ingredient.id }}"> {{ ingredient.name }} </label>
				<br/>
		    {% endfor %}
		{% endif %}
		<input type="submit" value="Show me some recipes!"/>
    </form>
</div>
<div id="featured_recipe">
	<h1>{{ featured_recipe.title_text }}</h1>
	{% if featured_recipe_ingredients %}
		<ul>
		{% for featured_ingredient in featured_recipe_ingredients %}
			<li>
				<b>{{ featured_ingredient.ingredient_name.name}}</b> {{ featured_ingredient.ingredient_quantity }}
			</li>
		{% endfor %}
		</ul>
	{% endif %}
	<img src="{{ featured_recipe.presentation_image_link }}"/>
	<p>{{ featured_recipe.process_description }}</p>
</div>